name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CompeyDev/setup-rokit@v0.1.2
      - name: StyLua check
        run: stylua --check src tests benchmark

  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CompeyDev/setup-rokit@v0.1.2
      - name: Selene
        run: selene src tests benchmark
